export const data = {
  id: '0',
  start: -1300000000,
  end: 100000,
  title: '',
  regime: 'Cosmos',
  hideBorder: true,
  exhibits: [],
  timelines: [
    {
      id: 't1',
      start: -1300000000,
      end: -1030000000,
      title: 'T1: Средний рифей',
      regime: 'Earth',
      exhibits: [
        {
          id: 'e1',
          time: -1165000000,
          title: 'Карты',
          contentItems: [{
            id: 'c1',
            title: 'Дмитровская Каграманян. ВИКА №1 Средний рифей.',
            description: '',
            mediaType: 'pdf',
            uri: 'https://raw.githubusercontent.com/slaylines/panoramica/main/data/T1P1.pdf',
          }],
        }, {
          id: 'e2',
          time: -1165000000,
          title: 'Общая характеристика',
          contentItems: [{
            id: 'c1',
            title: 'HTML test',
            description: '',
            mediaType: 'text',
            content: '<h1>Title</h1><ul><li>1</li><li>2</li></ul><a href="https://google.com">Google</a>',
          }],
        }, {
          id: 'e3',
          time: -1165000000,
          title: 'Геология',
          contentItems: [{
            id: 'c1',
            title: 'Long text test',
            description: '',
            mediaType: 'text',
            content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus enim id libero luctus, eu posuere turpis scelerisque. In ultrices maximus libero, ac cursus velit. Nullam et justo tristique, molestie mauris a, vestibulum justo. Curabitur nec accumsan orci. Aenean iaculis dolor in ipsum bibendum maximus. Curabitur ex odio, luctus at est id, ornare fringilla tortor. Suspendisse in bibendum sapien. Aenean luctus faucibus odio ut molestie.<br/><br/>Etiam ac elit nibh. Vestibulum at massa eros. Morbi vitae tincidunt tortor. In non justo vitae nisl placerat molestie quis a magna. Praesent tristique, dui vitae molestie tincidunt, odio nunc fermentum ligula, vel sodales libero ex in metus. Nunc accumsan nisi et elit rutrum, sit amet congue neque porttitor. Aenean nec vestibulum odio.',
          }],
        }, {
          id: 'e4',
          time: -1165000000,
          title: 'Биология',
          contentItems: [{
            id: 'c1',
            title: 'Youtube Video Test',
            description: '',
            mediaType: 'video',
            uri: 'https://www.youtube.com/embed/24UIq3_pNHM',
            thumbnail: 'http://img.youtube.com/vi/24UIq3_pNHM/mqdefault.jpg',
          }],
        }
      ],
      timelines: [],
    }, {
      id: 't2',
      start: -1030000000,
      end: -600000000,
      title: 'T2: Верхний рифей',
      regime: 'Earth',
      exhibits: [
        {
          id: 'e1',
          time: -815000000,
          title: 'Карты',
          contentItems: [
            {
              id: 'c1',
              title: 'Дмитровская Каграманян. ВИКА №1 Поздний рифей.',
              description: '',
              mediaType: 'pdf',
              uri: 'https://raw.githubusercontent.com/slaylines/panoramica/main/data/T2P1_1.pdf',
            }, {
              id: 'c2',
              title: 'Расположение ВВ 750 Верх рифей.',
              description: '',
              mediaType: 'pdf',
              uri: 'https://raw.githubusercontent.com/slaylines/panoramica/main/data/T2P1_2.pdf',
            },
          ],
        }, {
          id: 'e2',
          time: -815000000,
          title: 'Общая характеристика',
          contentItems: [],
        }, {
          id: 'e3',
          time: -815000000,
          title: 'Геология',
          contentItems: [],
        }, {
          id: 'e4',
          time: -815000000,
          title: 'Биология',
          contentItems: [],
        }
      ],
      timelines: [],
    }, {
      id: 't3',
      start: -600000000,
      end: -541000000,
      title: 'T3: Венд',
      regime: 'Earth',
      exhibits: [],
      timelines: [],
    }, {
      id: 't4',
      start: -541000000,
      end: -485000000,
      title: 'T4: Кембрий',
      regime: 'Earth',
      exhibits: [],
      timelines: [],
    }, {
      id: 't5',
      start: -485000000,
      end: -443800000,
      title: 'T5: Ордовик',
      regime: 'Earth',
      exhibits: [
        {
          id: 'e1',
          time: -464400000,
          title: 'Карты',
          contentItems: [
            {
              id: 'c1',
              title: 'Дмитровская Каграманян. ВИКА №1 Ордовик.',
              description: '',
              mediaType: 'pdf',
              uri: 'https://raw.githubusercontent.com/slaylines/panoramica/main/data/T5P1_1.pdf',
            }, {
              id: 'c2',
              title: 'Расположение ВВ 470 Ордовик.',
              description: '',
              mediaType: 'pdf',
              uri: 'https://raw.githubusercontent.com/slaylines/panoramica/main/data/T5P1_2.pdf',
            },
          ]
        }, {
          id: 'e2',
          time: -464400000,
          title: 'Общая характеристика',
          contentItems: [],
        }, {
          id: 'e3',
          time: -464400000,
          title: 'Геология',
          contentItems: [],
        }, {
          id: 'e4',
          time: -464400000,
          title: 'Биология',
          contentItems: [
            {
              id: 'c1',
              title: 'Картинка моря ордовика.',
              description: '',
              mediaType: 'image',
              uri: 'https://raw.githubusercontent.com/slaylines/panoramica/main/data/T5P4.jpg'
            }, {
              id: 'c2',
              title: 'Ссылки по Органике Ордовика.',
              description: '',
              mediaType: 'pdf',
              uri: 'https://raw.githubusercontent.com/slaylines/panoramica/main/data/T5P4_2.pdf'
            },
          ],
        },
      ],
      timelines: [],
    }, {
      id: 't6',
      start: -443800000,
      end: -419000000,
      title: 'T6: Силур',
      regime: 'Earth',
      exhibits: [],
      timelines: [],
    }, {
      id: 't7',
      start: -419000000,
      end: -358900000,
      title: 'T7: Девон',
      regime: 'Earth',
      exhibits: [],
      timelines: [],
    }, {
      id: 't8',
      start: -358900000,
      end: -298900000,
      title: 'T8: Каменугольный',
      regime: 'Earth',
      exhibits: [],
      timelines: [],
    }, {
      id: 't9',
      start: -298900000,
      end: -251900000,
      title: 'T9: Пермь',
      regime: 'Earth',
      exhibits: [],
      timelines: [],
    }, {
      id: 't10',
      start: -251900000,
      end: -201000000,
      title: 'T10: Триас',
      regime: 'Earth',
      exhibits: [],
      timelines: [],
    }, {
      id: 't11',
      start: -201000000,
      end: -145000000,
      title: 'T11: Юра',
      regime: 'Earth',
      exhibits: [],
      timelines: [],
    }, {
      id: 't12',
      start: -145000000,
      end: -66000000,
      title: 'T12: Мел',
      regime: 'Earth',
      exhibits: [],
      timelines: [],
    }, {
      id: 't13',
      start: -66000000,
      end: -23000000,
      title: 'T13: Палеоген',
      regime: 'Earth',
      exhibits: [],
      timelines: [],
    }, {
      id: 't14',
      start: -23000000,
      end: -2580000,
      title: 'T14: Неоген',
      regime: 'Earth',
      exhibits: [],
      timelines: [],
    }, {
      id: 't15',
      start: -2580000,
      end: 100000,
      title: '',
      regime: 'Earth',
      hideBorder: true,
      exhibits: [],
      timelines: [
        {
          id: 't15_1',
          start: -2580000,
          end: 0,
          title: 'T15: Антропоген',
          regime: 'Earth',
          exhibits: [],
          timelines: [],
        }, {
          id: 't15_2',
          start: 0,
          end: 100000,
          title: 'T16: Будущее',
          regime: 'Earth',
          exhibits: [],
          timelines: [],
        }
      ],
    },
  ],
};
